replicaCount: 1

image:
  repository: url-shortener
  tag: local
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: traefik
  host: localhost

postgres:
  database: urlshortener
  user: urlshortener
  password: urlshortener
  storageSize: 1Gi

app:
  databaseUrl: postgresql+psycopg://urlshortener:urlshortener@url-shortener-postgres:5432/urlshortener
