replicaCount: 2

image:
  repository: 805393736963.dkr.ecr.eu-west-1.amazonaws.com/url-shortener
  tag: sha-e985369
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: alb
  host: short.younessb.dev
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-1:805393736963:certificate/953d7f2d-73e5-47ee-83fb-ced4e1170e69"
  tls:
    enabled: false
    secretName: ""

postgres:
  storageSize: 10Gi
  existingSecret: url-shortener-postgres-secret

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

networkPolicy:
  enabled: true
