replicaCount: 1

image:
  repository: url-shortener
  tag: pr-placeholder
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: traefik
  host: pr-placeholder.preview.younessb.dev
  tls:
    enabled: true
    secretName: preview-younessb-dev-tls

postgres:
  storageSize: 1Gi

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

networkPolicy:
  enabled: true
