apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: url-shortener
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rose-meruem/project_kubernetes.git
    targetRevision: main
    path: charts/url-shortener
    helm:
      valueFiles:
        - values-local.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: url-shortener

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

