{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: url-shortener-postgres-pvc
  labels:
    {{- include "url-shortener.postgresLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgres.storageClass }}
  storageClassName: {{ .Values.postgres.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}
{{- end }}
