apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secret
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "{{ .Values.app.databaseUrl }}"
