{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "url-shortener.fullname" . }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "url-shortener.apiSelectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
